feat: support event logs extraction from the opcode logger
georgeroman/evm-tx-simulator pull request #1
Opened 2023-08-15 10:11 UTC by lljxx1

2023-08-16 05:45 UTC, georgeroman requested changes

2023-08-16 05:45 UTC, georgeroman commented on package.json
> +    "@ethereumjs/util": "^9.0.0",
I see we only use `bytesToHex` from this package. Isn't a similar method available in `ethers`? Would avoid adding a new package just for a single basic method.

2023-08-16 05:45 UTC, georgeroman commented on package.json
> +    "ts-jest": "^29.0.1",
`ts-jest`, `ts-node`, `@types/jest` and `jest` should all be `devDependencies` - they shouldn't be included in the build.

2023-08-19 07:48 UTC, georgeroman commented
@lljxx1 What do you think of making on-chain calls to get the test fixtures? Feels a bit extreme to save those million lines traces in the code when we can easily fetch them via `debug_traceTransaction` method on-demand.

2023-08-19 09:37 UTC, lljxx1 commented
@georgeroman I filtered out the unused opcodes, and the file size was down a little bit.

2023-08-25 06:45 UTC, merged